# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80f95c8bd0c0b14f20372391d1b2b17b"
name = "final-wishlist"
handle = "final-wishlist"
application_url = "https://balloon-appearance-jessica-bailey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products"




[auth]
redirect_urls = [
  "https://balloon-appearance-jessica-bailey.trycloudflare.com/auth/callback",
  "https://balloon-appearance-jessica-bailey.trycloudflare.com/auth/shopify/callback",
  "https://balloon-appearance-jessica-bailey.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "wishlist-heart-embed"
path = "extensions/wishlist-heart-embed"


[app_proxy]
subpath_prefix = "apps"
subpath        = "wishlist"
url            = "https://brief-till-newark-nebraska.trycloudflare.com/apps/wishlist"
